# Generated by Django 2.1.2 on 2018-10-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0002_auto_20181018_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='password',
        ),
    ]
