# Generated by Django 2.1.2 on 2018-10-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0003_remove_citizen_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('students', models.ManyToManyField(related_name='subject_students', to='relationships.Student')),
            ],
        ),
        migrations.AlterField(
            model_name='citizen',
            name='id_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
